# Generated by Django 2.2.6 on 2020-03-22 19:03

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('insertupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InsertUpdate')),
                ('address1', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('Address_Type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Address_Type', to='core.AddressType')),
            ],
            bases=('core.insertupdate', models.Model),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('insertupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InsertUpdate')),
                ('Total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.insertupdate', models.Model),
        ),
        migrations.CreateModel(
            name='OrderShop',
            fields=[
                ('insertupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InsertUpdate')),
                ('Items_Total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('DeliveryCharges', models.IntegerField()),
                ('Note', models.TextField(max_length=100)),
                ('Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order', to='core.Order')),
            ],
            bases=('core.insertupdate', models.Model),
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('setuptable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SetupTable')),
            ],
            options={
                'verbose_name_plural': 'Order Statuses',
            },
            bases=('core.setuptable',),
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('setuptable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SetupTable')),
            ],
            options={
                'verbose_name_plural': 'Payment Statuses',
            },
            bases=('core.setuptable',),
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('setuptable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SetupTable')),
            ],
            bases=('core.setuptable',),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('insertupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InsertUpdate')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('barcode', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(default='pics_default/default_product.png', upload_to=core.models.product_image_file_path)),
                ('slug', models.SlugField(blank=True, default='', max_length=255, null=True)),
            ],
            bases=('core.insertupdate', models.Model),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('setuptable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SetupTable')),
            ],
            bases=('core.setuptable',),
        ),
        migrations.CreateModel(
            name='ProductUnitType',
            fields=[
                ('setuptable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SetupTable')),
            ],
            bases=('core.setuptable',),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('insertupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InsertUpdate')),
                ('OpeningTime', models.TimeField()),
                ('ClosingTime', models.TimeField()),
                ('MinimumOrder', models.IntegerField()),
                ('DeliveryCharges', models.IntegerField()),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shop_Address', to='core.Address')),
            ],
            bases=('core.insertupdate', models.Model),
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('setuptable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SetupTable')),
            ],
            bases=('core.setuptable',),
        ),
        migrations.CreateModel(
            name='ShopStatus',
            fields=[
                ('setuptable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SetupTable')),
            ],
            options={
                'verbose_name_plural': 'Shop Statuses',
            },
            bases=('core.setuptable',),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Address_Types',
        ),
        migrations.CreateModel(
            name='ShopProductCategory',
            fields=[
                ('insertupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InsertUpdate')),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_Category', to='core.ProductCategory')),
                ('Shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shop_product', to='core.Shop')),
            ],
            bases=('core.insertupdate', models.Model),
        ),
        migrations.CreateModel(
            name='ShopProduct',
            fields=[
                ('insertupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InsertUpdate')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Available', models.BooleanField(default=False)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='core.Product')),
                ('Shop_Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shop_Product_Category', to='core.ShopProductCategory')),
            ],
            bases=('core.insertupdate', models.Model),
        ),
        migrations.AddField(
            model_name='shop',
            name='Shop_Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shop_Category', to='core.ShopCategory'),
        ),
        migrations.AddField(
            model_name='shop',
            name='Shop_Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shop_Status', to='core.ShopStatus'),
        ),
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductSubcategory',
            fields=[
                ('setuptable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SetupTable')),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductCategory', to='core.ProductCategory')),
            ],
            options={
                'verbose_name_plural': 'Product Categories',
            },
            bases=('core.setuptable',),
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('setuptable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.SetupTable')),
                ('Product_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BrandProductCategory', to='core.ProductCategory')),
            ],
            bases=('core.setuptable',),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Brand', to='core.ProductBrand'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Subcategory', to='core.ProductSubcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Unit_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Unit_Type', to='core.ProductUnitType'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('insertupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InsertUpdate')),
                ('arrears', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid', models.DecimalField(decimal_places=2, max_digits=8)),
                ('remaining', models.DecimalField(decimal_places=2, max_digits=8)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField()),
                ('Payment_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_Type', to='core.PaymentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.insertupdate', models.Model),
        ),
        migrations.CreateModel(
            name='OrderShopProduct',
            fields=[
                ('insertupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InsertUpdate')),
                ('Quantity', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('Note', models.TextField(max_length=100)),
                ('Order_Shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Shop', to='core.OrderShop')),
                ('Shop_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Shop_Products', to='core.ShopProduct')),
            ],
            bases=('core.insertupdate', models.Model),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='Order_Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Status', to='core.OrderStatus'),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='Payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Payment', to='core.Payment'),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='Payment_Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_Status', to='core.PaymentStatus'),
        ),
        migrations.AddField(
            model_name='ordershop',
            name='Shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Order_Shop', to='core.Shop'),
        ),
        migrations.AddField(
            model_name='address',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_address', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.City'),
        ),
    ]
