# Generated by Django 2.2.6 on 2020-03-24 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200323_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverOrder',
            fields=[
                ('insertupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InsertUpdate')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Driver_Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Driver_Order', to='core.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Driver_User', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('core.insertupdate', models.Model),
        ),
    ]
