# Generated by Django 2.2.6 on 2020-03-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_driverorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('shop', 'shop'), ('customer', 'customer'), ('delivery', 'delivery'), ('owner', 'owner')], default='owner', max_length=10),
        ),
    ]
