# Generated by Django 2.2.6 on 2020-04-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
    ]
