# Generated by Django 2.2.6 on 2020-04-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='DeliveryCharges',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='shop',
            name='MinimumOrder',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
