# Generated by Django 2.2.6 on 2020-04-08 15:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200408_2008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name_plural': 'Product Subcategories'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='pics_default/default_product.png', upload_to=core.models.product_image_file_path),
        ),
    ]
