# Generated by Django 2.2.6 on 2020-04-08 16:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200408_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='pics_default/default_product.jpg', upload_to=core.models.product_image_file_path),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(default='pics_default/default_product.jpg', upload_to=core.models.product_image_file_path),
        ),
    ]
