# Generated by Django 2.2.6 on 2020-04-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200411_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='MaximumOrder',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
    ]
