# Generated by Django 2.2.6 on 2020-04-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_shop_maximumorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershop',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, null=True),
        ),
    ]
