# Generated by Django 2.2.6 on 2020-04-12 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_ordershop_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Shop_Name',
        ),
    ]
