# Generated by Django 2.2.6 on 2020-04-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200413_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='ClosingTime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='OpeningTime',
            field=models.CharField(max_length=100),
        ),
    ]
