# Generated by Django 2.2.6 on 2020-04-13 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200413_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopproduct',
            name='Available',
        ),
    ]
