# Generated by Django 2.2.6 on 2020-04-14 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_shopproduct_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='Shop_Category',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='Shop_Categoryy', to='core.ShopCategory'),
            preserve_default=False,
        ),
    ]
