# Generated by Django 2.2.6 on 2020-04-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_productcategory_shop_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='DeliveryCharges',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
