# Generated by Django 2.2.6 on 2020-04-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200415_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='DeliveryCharges',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
    ]
