# Generated by Django 2.2.6 on 2020-04-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200415_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershop',
            name='Payment',
        ),
        migrations.RemoveField(
            model_name='ordershop',
            name='Payment_Status',
        ),
    ]
