# Generated by Django 2.2.6 on 2020-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200422_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershopproduct',
            name='Weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
