# Generated by Django 2.2.6 on 2020-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20200422_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershop',
            name='Note',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordershopproduct',
            name='Note',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
