# Generated by Django 2.2.6 on 2020-04-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200422_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershop',
            name='Order_Status',
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Status',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='Order_Status', to='core.OrderStatus'),
            preserve_default=False,
        ),
    ]
