# Generated by Django 2.2.6 on 2020-05-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20200426_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
