# Generated by Django 2.2.6 on 2020-05-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Note',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
