# Generated by Django 2.2.6 on 2020-05-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200509_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Note',
            field=models.TextField(default='', max_length=500),
        ),
    ]
