# Generated by Django 2.2.6 on 2020-05-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200509_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
