# Generated by Django 2.2.6 on 2020-05-09 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200509_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('insertupdate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.InsertUpdate')),
                ('location', models.CharField(max_length=200)),
            ],
            bases=('core.insertupdate', models.Model),
        ),
    ]
