# Generated by Django 2.2.6 on 2020-05-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_servicerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='Note',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
