from django.contrib import admin
from . import models

admin.site.register(models.User)
admin.site.register(models.Gender)
admin.site.register(models.Country)
admin.site.register(models.City)
admin.site.register(models.ProfileStatus)
admin.site.register(models.AddressType)
admin.site.register(models.ProductCategory)
admin.site.register(models.ProductSubcategory)
admin.site.register(models.ProductBrand)
admin.site.register(models.ProductUnitType)
admin.site.register(models.ShopCategory)
admin.site.register(models.ShopStatus)
admin.site.register(models.OrderStatus)
admin.site.register(models.PaymentStatus)
admin.site.register(models.PaymentType)
admin.site.register(models.Profile)
admin.site.register(models.Address)
admin.site.register(models.Product)
admin.site.register(models.Shop)
admin.site.register(models.ShopProductCategory)
admin.site.register(models.ShopProduct)
admin.site.register(models.Order)
admin.site.register(models.OrderShop)
admin.site.register(models.OrderShopProduct)
admin.site.register(models.DriverOrder)
admin.site.register(models.Payment)
admin.site.register(models.ServiceRequest)
